### PR TITLE
page size 100

### PR DESCRIPTION
**Pull request by zicjin**

### CODE REVIEW

**Comment by zicjin** [comment]
.

**Comment by zicjin** [comment]
.

**Comment by zicjin** [comment]
1 All 6 ACCESS_TOKEN are invalid and used in the wrong way? [document](https://developer.github.com/v3/#basic-authentication)

2 
```
// star-history.service.ts
// count step (to get indexes)
const step = NUMBER_OF_SAMPLES / samplesForPage;
```
It's very confusing. It took me a lot of time to understand the original meaning of this code. It just so happens that the default pagesize is 30, so you use the NUMBER_OF_SAMPLES constant?
In addition, I learned from [here](https://github.com/seladb/StarTrack-js/blob/master/src/utils/GitHubUtils.js#L3) that pagesize can be changed, if changed to a larger value, does it mean that ACCESS_TOKEN usage can be reduced?

3 I got [this compilation error](https://github.com/grpc/grpc-node/issues/922) of grpc in the windows. Unless you downgrade to node v10 or update firebase to the latest version. So I updated all the packages to the latest version using npm-check by the way.

**Review by pnowy — COMMENTED** [review]
Can we split this dependencies upgrade? I mean as a separate pull request?

**Comment by pnowy** [comment]
Ad.1 Yes - the Github deprecated the approach (https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters) but I think these tokens should be removed at all (those tokens are not active anymore).

I think the right approach would be to add some login screen to user Github auth in order to retrieve the token (without scopes - they are not needed in this case) or some additional modal to provide access token in order to increase rate limit - otherwise there will be the problem.

Ad.2 The constant `NUMBER_OF_SAMPLES` was the number of samples for chart (for popular repository there could be a lot of pages/stars so it was enough to get only 30 samples from different pages to get correct chart). But yeah - I can agree that this code can be refactored because is quite confusing and not easy to read.

I would split this changes int smaller separte changes.

Ad. 3. Lets upgrade it as separate PR. Will you do that or should I?

**Comment by zicjin** [comment]
I built a new pull request.

In fact, I prefer the way auth token works in this project. There are many star-history projects that are authorized by the user OAuth elsewhere. But I think the current way of using Auth token is advantageous and convenient enough for the product.  OAuth is always a threshold. If we can collect 20 token, we can have 100,000 requests/per hour , it's enough. And over time, the cache hit ratio of popular repo will become higher and higher.

**Pull request closed without merging**
